CREATE DATABASE QuanLyCuaHangTraChanh
USE QuanLyCuaHangTraChanh
GO

--KICH THUOC
CREATE TABLE KICHTHUOC(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaKT VARCHAR(30) UNIQUE,
	TenKT NVARCHAR(50) DEFAULT NULL,
	Gia DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
GO
--SAN PHAM
CREATE TABLE SANPHAM (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdKT UNIQUEIDENTIFIER,
	IdDM UNIQUEIDENTIFIER,
	MaSP VARCHAR(30) UNIQUE, 
	TenSP NVARCHAR(50) DEFAULT NULL,
	GiaNhap DECIMAL(20,0) DEFAULT 0,
	GiaBan DECIMAL(20,0) DEFAULT 0,
	SoLuongTon int,
	MoTa nvarchar(50),
	TrangThai INT DEFAULT 0
)
GO
--Hinh Anh SP
Create table HINHANH(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdSanPham UNIQUEIDENTIFIER,
	TenHA NVARCHAR(50) DEFAULT NULL,
	DuongDan Varchar(100),
	TrangThai INT DEFAULT 0
)
--DanhMuc-TheLoai
CREATE TABLE DANHMUC(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdTL UNIQUEIDENTIFIER,
	MaTL VARCHAR(30) UNIQUE,
	TenTL NVARCHAR(50) DEFAULT NULL,
	TrangThai INT DEFAULT 0
)
GO

--BAN
CREATE TABLE BAN(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdKV UNIQUEIDENTIFIER,
	MaBan VARCHAR(30) DEFAULT NULL,
	TenBan Nvarchar(30),
	SoNguoi int,
	TrangThai INT DEFAULT 0
)

--KHUYEN MAI
CREATE TABLE KHUYENMAI(
	Id  UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(50) DEFAULT NULL,
	NgayBatDau DATETIME DEFAULT NULL,
	NgayKetThuc DATETIME DEFAULT NULL,
	MucGiamGiaPhanTram DECIMAL(20,0),
	MucGiamGiaTienMat DECIMAL(20,0),
	DieuKienGiamGia NVARCHAR(50) DEFAULT NULL,
	LoaiGiamGia NVARCHAR(50) DEFAULT NULL,
	TrangThai INT DEFAULT 0,
)
GO
--SPKhuyenMai
Create table SPKHUYENMAI(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdKM UNIQUEIDENTIFIER,
	IdSP UNIQUEIDENTIFIER,
	DonGia DECIMAL(20,0) DEFAULT 0,
	SoTienConLai DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
--HOA DON
CREATE TABLE HOADON(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdNV UNIQUEIDENTIFIER,
	IdKH UNIQUEIDENTIFIER,
	IdBAN UNIQUEIDENTIFIER,
	MaHD VARCHAR(50) UNIQUE,
	NgayTao DATETIME DEFAULT NULL,
	NgayThanhToan DATETIME DEFAULT NULL,
	NgayShip DATETIME DEFAULT NULL,
	TienShip DECIMAL(20,0) DEFAULT 0,
	TienCoc DECIMAL(20,0) DEFAULT 0,
	NgayNhan DATETIME DEFAULT NULL,
	TenNguoiNhan VARCHAR(MAX) DEFAULT NULL,
	DiaChi VARCHAR(MAX) DEFAULT NULL,
	TongTien DECIMAL(20,0) DEFAULT 0,
	SDTNguoiNhan VARCHAR(30) DEFAULT NULL,
	SDTNguoiShip VARCHAR(30) DEFAULT NULL,
	TenNguoiShip VARCHAR(MAX) DEFAULT NULL,
	PhanTramGiamGia DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
GO
--HOA DON CHI TIET
CREATE TABLE HOADONCHITIET(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdHD UNIQUEIDENTIFIER,
	IdSP UNIQUEIDENTIFIER,
	IdDa UNIQUEIDENTIFIER,
	IdDuong UNIQUEIDENTIFIER,
	SoLuong DECIMAL(20,0) DEFAULT 0, 
	DonGia DECIMAL(20,0) DEFAULT 0,
	GiaDuong DECIMAL(20,0) DEFAULT 0,
	GiaDa DECIMAL(20,0) DEFAULT 0,
	ThanhTien DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0

)
GO
--MUC DUONG
CREATE TABLE MUCDUONG(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaD VARCHAR(20) UNIQUE,
	TenD NVARCHAR(30) DEFAULT NULL,
	GiaD DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
--MUCDA
CREATE TABLE MUCDA(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaD VARCHAR(20) UNIQUE,
	TenD NVARCHAR(30) DEFAULT NULL,
	GiaD DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
--HINH THUC THANH TOAN
CREATE TABLE HINHTHUCTHANHTOAN(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdHD UNIQUEIDENTIFIER,
	IdNV UNIQUEIDENTIFIER,
	Ma VARCHAR(20) UNIQUE,
	NgayTao DATETIME DEFAULT NULL,
	NgaySua DATETIME DEFAULT NULL,
	LoaiHinhThanhToan NVARCHAR(50) DEFAULT NULL,
	TongTienThanhToan DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
--NHAN VIEN
CREATE TABLE NHANVIEN(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(30) DEFAULT NULL,
	GioiTinh NVARCHAR(10) DEFAULT NULL,
	NgaySinh DATE DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	Sdt VARCHAR(30) DEFAULT NULL,
	GhiChu NVARCHAR(50) DEFAULT NULL,
	MatKhau VARCHAR(MAX) DEFAULT NULL,
	TrangThai INT DEFAULT 0,
	Anh nvarchar(50) NULL,
	NgayTao DATETIME DEFAULT NULL,
	IdCV UNIQUEIDENTIFIER,
)
GO
--KHACH HANG
CREATE TABLE KHACHHANG(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(30) DEFAULT NULL,
	NgaySinh DATE DEFAULT NULL,
	Sdt VARCHAR(30) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	GioiTinh NVARCHAR(10) DEFAULT NULL,
	GhiChu NVARCHAR(50) DEFAULT NULL,
	TrangThai INT DEFAULT 0
)
GO
--CHUC VU
CREATE TABLE CHUCVU(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaCV VARCHAR(20) UNIQUE,
	TenCV NVARCHAR(30) DEFAULT NULL,
	GhiChu NVARCHAR(50) DEFAULT NULL,
	TrangThai INT DEFAULT 0
)



--TẠO MỐI QUAN HỆ GIỮA CÁC BẢNG
--SAN PHAM  - KICH THUOC
ALTER TABLE SANPHAM ADD FOREIGN KEY(IdKT) REFERENCES KICHTHUOC(Id)
--SAN PHAM  - DANH MUC
ALTER TABLE SANPHAM ADD FOREIGN KEY(IdDM) REFERENCES DANHMUC(Id)
--HINH ANH - SAN PHAM
ALTER TABLE HINHANH ADD FOREIGN KEY(IdSanPham) REFERENCES SANPHAM(Id)
-- SP KHUYEM MAI -- KHUYEN MAI
ALTER TABLE SPKHUYENMAI ADD FOREIGN KEY(IdKM) REFERENCES KHUYENMAI(Id)
-- SP KHUYEM MAI -- SAN PHAM
ALTER TABLE SPKHUYENMAI ADD FOREIGN KEY(IdSP) REFERENCES SANPHAM(Id)
--HOA DON - KHACH HANG
ALTER TABLE HOADON ADD FOREIGN KEY(IdKH) REFERENCES KHACHHANG(Id)
--HOA DON - NHAN VIEN
ALTER TABLE HOADON ADD FOREIGN KEY(IdNV) REFERENCES NHANVIEN(Id)
--HOA DON - BAN
ALTER TABLE HOADON ADD FOREIGN KEY(IdBAN) REFERENCES BAN(Id)
--HINH THUC THANH TOAN -NHAN VIEN
ALTER TABLE HINHTHUCTHANHTOAN ADD FOREIGN KEY(IdNV) REFERENCES NHANVIEN(Id)
--HINH THUC THANH TOAN -HOA DON
ALTER TABLE HINHTHUCTHANHTOAN ADD FOREIGN KEY(IdHD) REFERENCES HOADON(Id)
--NHAN VIEN - CHUC VU
ALTER TABLE NHANVIEN ADD FOREIGN KEY(IdCV) REFERENCES CHUCVU(Id)
--HOA DON CHI TIET -MUC DUONG
ALTER TABLE HOADONCHITIET ADD FOREIGN KEY(IdDUONG) REFERENCES MUCDUONG(Id)
--HOA DON CHI TIET -MUC DA
ALTER TABLE HOADONCHITIET ADD FOREIGN KEY(IdDA) REFERENCES MUCDA(Id)
--HOA DON CHI TIET -SAN PHAM
ALTER TABLE HOADONCHITIET ADD FOREIGN KEY(IdSP) REFERENCES SANPHAM(Id)
--HOA DON CHI TIET -HOA DON
ALTER TABLE HOADONCHITIET ADD FOREIGN KEY(IdHD) REFERENCES HOADON(Id)
-- SELF JOIN DANH MUC VS DANHMUC(THELOAI)
ALTER TABLE DANHMUC ADD FOREIGN KEY(IdTL) REFERENCES DANHMUC(Id)

DROP DATABASE QuanLyCuaHangTraChanh





